### ISSUE TITLE
no tables while using pry-rails

### ISSUE THREAD

**Issue by panaak** [hirber/hirber#4]
There are no tables while also using `pry` from https://github.com/rweng/pry-rails.

**Comment by adlugopolski** [comment]
I've took a very brief look on `pry-rails` and decided to give it a go. Check out version 0.8.4. It should now display tables (for `ActiveRecord` models)  by default. 

![image](https://user-images.githubusercontent.com/15016053/107883727-db934400-6ef0-11eb-8c66-d3cd93a2ffdb.png)

**Comment by panaak** [comment]
beautiful! it works great, thanks a bunch! .)
